### ISSUE TITLE
Bug when reading cell-center coordinate with athdf() in athena_read.py

### ISSUE THREAD

**Issue by astrodoo** [PrincetonUniversity/athena-public-version#12]
Dear developer,

I think there is a little bug in athdf function of athena_read.py 
that the cell-center coordinate (e.g. data['x1v']) dumps only sing value not a 1-D array. 

I checked the code and found that the array index was missing ( 334 line in the code ).

      for i in range(nx):
        data['x'+repr(d)+'v'] = \
               center_func(data['x'+repr(d)+'f'][i], data['x'+repr(d)+'f'][i+1])

--> 

      for i in range(nx):
        data['x'+repr(d)+'v'][i] = \
               center_func(data['x'+repr(d)+'f'][i], data['x'+repr(d)+'f'][i+1])

Thanks for your efforts on the development of the code.

Best,
Doosoo

**Comment by c-white** [comment]
Yes, this is indeed a bug in the current version. It will be fixed in the next public release. In the meantime, the suggested change is exactly what needs to be done.

**Comment by felker** [comment]
@c-white, was this fixed in 1.1.0 or 1.1.1?

**Comment by c-white** [comment]
@felker Very much so - this was fixed in 6f72e7f on the development repo, on 2017-02-13.

**Comment by felker** [comment]
I figured as much but wanted to check! Thanks.
