### ISSUE TITLE
Improve VisIt integration with HDF5/XDMF outputs with time-dependent MeshBlock counts

### ISSUE THREAD

**Issue by markcmiller86** [PrincetonUniversity/athena-public-version#14]
Sorry to read about your VisIt issues.

The situation can be improved by adopting some convention for Xdmf metadata to communicate to VisIt that the mesh block count is _time varying_. For example, using Xdmf _information_ element such as...
```
<Information Name="TimeVaryingMetaData" Value="True"/>
```
We can adjust the Xdmf plugin in VisIt to then look for this additional tag and, if found, make VisIt operate such that it does not assume block count is the same across time steps.

**Comment by felker** [comment]
Hi Mark, 
Thanks again for your helpful replies to my [visit-users email list thread](https://elist.ornl.gov/pipermail/visit-users/2018-August/021587.html). 

I can add this information element to the `MakeXDMF()` function in [`outputs/athena_hdf5.cpp`](https://github.com/PrincetonUniversity/athena-public-version/blob/4d0e425e8eb46ae75a053b71cb2654e196e325bf/src/outputs/athena_hdf5.cpp#L789) on the private development repository and test it with VisIt before the next public version release to this repository. 

Would the matching change to the XDMF plugin be present in the next VisIt release (3.0?)?

*Note*: this would address some of the concerns in #4

**Comment by markcmiller86** [comment]
Yes, easily. But, I would want an example dataset first, ok?

Mark


"Kyle Gerard Felker" wrote:


Would the matching change to the XDMF plugin be present in the next VisIt release (3.0?)?

**Comment by felker** [comment]
Here is a tarball with an example XDMF database containing 11 time-sliced outputs with the new metadata tag added: [new_xdmf_db_example.tar.gz](https://github.com/PrincetonUniversity/athena-public-version/files/2295128/new_xdmf_db_example.tar.gz)

Note, this is a 2D output. Let me know if you would like a 3D example or anything else.

**Comment by felker** [comment]
@markcmiller86 --- did this make it into the VisIt 3.0.1 release? 

I just noticed that there is a checkbox for Preferences > "Treat all databases as time-varying", but that switch was also present in VisIt 2.13.1 and probably does not relate to this functionality, correct?

**Comment by markcmiller86** [comment]
Sorry...dropped the ball on that. Just added it in https://github.com/visit-dav/visit/pull/3830

**Comment by felker** [comment]
Thanks a lot!

**Comment by markcmiller86** [comment]
@brugger1 ... apologies but it looks like I accidentally committed this change direct to 3.0RC. I wanted it there but should have employed a branch to do it. Does this impact you negatively?

**Comment by markcmiller86** [comment]
> I just noticed that there is a checkbox for Preferences > "Treat all databases as time-varying", but that switch was also present in VisIt 2.13.1 and probably does not relate to this functionality, correct?

Not quite. That switch would have helped. But, its a nuclear option in that effects *all* databases, *all* the time. This solution allows data producer to inform VisIt how to behave correctly by annotating the database itself as necessary. Presumably, the data producer will add

```
<Information Name="TimeVaryingMetaData" Value="True"/>
```

**only** when the block count is indeed varying.

**Comment by brugger1** [comment]
It shouldn’t be a problem.
