### ISSUE TITLE
Energy conservation

### ISSUE THREAD

**Issue by Yotag** [PrincetonUniversity/athena-public-version#15]
Hello,
What level of energy conservation can I expect from Athena's simulation? Are there conservation tests available to show Athena's consistency in this matter?
I am working on a simulation with a gravitational source term added to the problem generator. Should I expect a change to the accuracy of the conservation? If so, at what levels? Are there any ways to improve it?
Regards, Yotam.

**Comment by felker** [comment]
Since Athena++ is built on a Godunov-type method, the core hydro and MHD solvers should conserve energy to machine precision. 

I'll let @changgoo remark on the effect of gravitational source terms.

**Comment by changgoo** [comment]
To make gravity source terms conservative, one needs special care (e.g., http://adsabs.harvard.edu/abs/2013NewA...19...48J). This is not implemented in the current Athena. 

Any source terms that are added as an operator-split fashion will hurt energy conservation. I believe @pdmullen had an experience of testing gravity source terms.

**Comment by pdmullen** [comment]
Hey @Yotag,

Thanks for the question! My experience with gravity in Athena++ is with the included FFT self-gravity solver.  As @changgoo mentioned, updates to energy from self-gravity are handled through source terms, not by constructing fluxes, and therefore total energy (when self-gravity is enabled) is not expected to be conserved to machine precision.  

If you are not using the FFT self-gravity solver, but are rather implementing your own source terms, I would recommend looking at `self_gravity.cpp` for reference.  

I have done some test problems for the FFT self-gravity solver.  One such test problem involves advecting a 1-D self-gravitating sheet once across a periodic domain.  

[compare.pdf](https://github.com/PrincetonUniversity/athena-public-version/files/2454169/compare.pdf)

This problem involves adiabatic hydro with self-gravity and thus employs the self-gravity energy source terms.  The L_1 error for this problem converges at second order for both the vl2 and rk2 integrators.  

[conv.pdf](https://github.com/PrincetonUniversity/athena-public-version/files/2454170/conv.pdf)

If interested, below is the time evolution of the total energy in these 1-D self-gravitating disk simulations at different resolutions.  Recall that for self-gravitating systems the total energy (without B-fields) is given as 

<a href="http://www.codecogs.com/eqnedit.php?latex=E_{\textrm{tot}}&space;=&space;\int&space;d^3&space;\textbf{x}&space;\left(&space;\frac{1}{2}&space;\rho&space;v^2&space;&plus;&space;\frac{p}{\gamma-1}&space;&plus;&space;\frac{1}{2}&space;\rho&space;\phi&space;\right)" target="_blank"><img src="http://latex.codecogs.com/gif.latex?E_{\textrm{tot}}&space;=&space;\int&space;d^3&space;\textbf{x}&space;\left(&space;\frac{1}{2}&space;\rho&space;v^2&space;&plus;&space;\frac{p}{\gamma-1}&space;&plus;&space;\frac{1}{2}&space;\rho&space;\phi&space;\right)" title="E_{\textrm{tot}} = \int d^3 \textbf{x} \left( \frac{1}{2} \rho v^2 + \frac{p}{\gamma-1} + \frac{1}{2} \rho \phi \right)" /></a>

[etot.pdf](https://github.com/PrincetonUniversity/athena-public-version/files/2454173/etot.pdf)

Best,
Patrick
