### ISSUE TITLE
Occasional segfault from hydro_diffusion

### ISSUE THREAD

**Issue by jonosquire** [PrincetonUniversity/athena-public-version#18]
Hello, 

I just found a very minor issue, which caused a segfault for me on some compilers. In the `HydroDiffusion` constructor, in hydro_diffusion.cpp, the `kappa_iso` and `kappa_aniso` parameters are only set if it is a non-baratropic EOS. In other functions, e.g., `SetHydroDiffusivity` they are then used in various if statements, which occasionally causes a segfault. Of course, this only shows up with an isothermal EOS, just thought it could be good to fix up. 

Cheers,
Jono

**Comment by felker** [comment]
Thank you 👍  Patched in development version, lookout for the fix in the next release.
