### ISSUE TITLE
Restart files from an AMR simulation might be corrupted

### ISSUE THREAD

**Issue by Yotag** [PrincetonUniversity/athena-public-version#19]
Hi, I am running an AMR sim. with some .rst for backup. The sim failed at some point (which happens every now and then, something related to my machine) and trying to use the .rst file to restart yields an error: 
"FATAL ERROR in FindNeighbor
Neighbor search failed. The Block Tree is broken."
Could you please explain what is the meaning of this error ? Is there an easy fix?
Thanks,
Yotam.

**Comment by tomidakn** [comment]
It likely means that your restart file is broken, for example the simulation was terminated halfway while the code was making output, and it does not contain all the MeshBlocks. Please check the file size, and if it is too small probably this is the case. In the case the only way to save it is to rerun the calculation from an earlier restart file.

**Comment by Yotag** [comment]
I thought this might be the case, but the simulation was terminate quite a while after the .rst time step, and unfortunately earlier .rst files give the same error...

**Comment by tomidakn** [comment]
If the earlier file is corrupted, something might be wrong. Currently I am quite busy, but if you could share the input file and problem generator, I may be able to take a look at it.

**Comment by felker** [comment]
Closing due to lack of information.
