### ISSUE TITLE
Extra hook in Mesh might be broadly useful

### ISSUE THREAD

**Issue by morganemacleod** [PrincetonUniversity/athena-public-version#20]
I have found a mesh-level hook for user work extremely useful for many of the problems I've set up. This is a hook that lives in `pgen/` that gets called at the end of each timestep. 

One example usage is computing diagnostics that depend on global quantities: for example I first summed a center of mass, then broadcast that value, then compute an angular momentum relative to that center of mass -- each time looping over all of the MeshBlocks.  Another example is when you have pgen-specific global quantities that you want to update once per step rather than once per MeshBlock. 

I implemented this as follows:
1) add function declaration to `mesh.hpp` 
2) add function definition to `default_pgen.cpp`
3) call last at the end of the task list just before a new step

Here are a couple of excerpts:
I declare the function in `mesh.hpp`:
```
void MeshUserWorkInLoop(ParameterInput *pin);  // MM: in ../pgen
```

And I put a "do nothing" version in the `default_pgen.cpp`:
```
//========================================================================================
// MM:
//! \fn void Mesh::MeshUserWorkInLoop(void)
//  \brief Function called once every time step for user-defined work.
//========================================================================================

void __attribute__((weak)) Mesh::MeshUserWorkInLoop(ParameterInput *pin)
{
  // do nothing
  return;
}'
```

If this seems like a broadly useful idea I'm happy to contribute to putting it in place but obviously wanted to run it by folks first. 

Morgan

**Comment by tomidakn** [comment]
I agree with this and it should be easy to add.

**Comment by msbc** [comment]
Similarly, I've had to add `Mesh::UserWorkBeforeOutput(ParameterInput *pin)` for a project before.

**Comment by dfielding14** [comment]
This would be very useful for me. I've hacked together similar functionality recently

**Comment by tomidakn** [comment]
I will add Mesh::UserWorkInLoop, and it will be called after everything is done in each loop including MeshBlock::UserWorkInLoop.

**Comment by tomidakn** [comment]
This will be included in the next release.
