### ISSUE TITLE
Error linking libnoise library due to flag order; add separate --lib, --lib_path flags to configure.py

### ISSUE THREAD

**Issue by trwaters** [PrincetonUniversity/athena-public-version#21]
Hi dev team - I'm trying to link an external library (libnoise) that's been successfully built on linux.  On my Mac, it works fine to use `--cflag="-lnoise"` after doing the `--include=` and `--lib=` in the configure step.  But on linux, it seems I'm running into this issue 
[https://stackoverflow.com/questions/2624238/c-undefined-references-with-static-library](https://stackoverflow.com/questions/2624238/c-undefined-references-with-static-library)
If I manually edit the Makefile to add `-lnoise` then Athena++ compiles, but if there is already a built-in way I'd love to know as for sure I'll forget I had to resort to this a couple months from now.  Thanks

**Comment by c-white** [comment]
I think we can easily add a configure flag for `-l` options just like we have for `-I` and `-L`. Perhaps the new feature can be `--lib` and the old `-L` can be changed to `--lib_path` or something.

**Comment by c-white** [comment]
Actually, I'd be interested in knowing the exact configure commands you call, and what the script reports as "Compilation command" at the very end.

**Comment by tomidakn** [comment]
While it is not difficult to add a new configuration option, this can be easily done using the `--cflag` configuration option already available. Take a look at the documentation as well as the help message of the configuration script `configure.py -h`.
https://github.com/PrincetonUniversity/athena-public-version/wiki/Configuring

**Comment by trwaters** [comment]
Hi Kengo.  What I'm reporting is that `--cflag` works on Mac but not linux due to the issue I linked to.  

Chris, here's my configure call
`python configure.py --prob=$prob --coord=spherical_polar -mpi --flux=hllc --nghost=3 -hdf5 --hdf5_path=/usr/projects/hpcsoft/toss3/grizzly/hdf5/1.8.16_intel-17.0.4_intel-mpi-5.1.3 --include=/users/waterst3/local/libnoise/dist/include --lib=/users/waterst3/local/libnoise/dist/Release --cflag="-lnoise"`

Here's what that spits out
`Linker flags:             -L/usr/projects/hpcsoft/toss3/grizzly/hdf5/1.8.16_intel-17.0.4_intel-mpi-5.1.3/lib -L/users/waterst3/local/libnoise/dist/Release  -lhdf5`
`Compilation command:     mpicxx  -I/usr/projects/hpcsoft/toss3/grizzly/hdf5/1.8.16_intel-17.0.4_intel-mpi-5.1.3/include -O3 -std=c++11 -lnoise -I/users/waterst3/local/libnoise/dist/include`

This is what doesn't work on the cluster.  If I insert `-lnoise` before `-lhdf5` in the Makefile, then it works.

**Comment by tomidakn** [comment]
Oh I see the point, sorry. The easiest workaround is just to specify all the compiler options using `--cflag` instead of `--lib` and `--include` in the right ordering. But then I think we can add the library option as Chris proposed.

**Comment by tomidakn** [comment]
Or you can just set the environment variables such as `LD_LIBRARY_PATH` etc.?

**Comment by c-white** [comment]
Ah yes, the libraries must come after the object files in the link command -- see https://gcc.gnu.org/onlinedocs/gcc/Link-Options.html under "It makes a difference where in the command you write this option..." The Makefile template already links according to `... $(CXXFLAGS) ... $(OBJ_FILES) ... $(LDLIBS)`, so we just need a convenient user interface for setting `$(LDLIBS)`. This should be in the next release.

**Comment by trwaters** [comment]
Just tried doing everything with `cflag` and it doesn't work.  That is, I get an "undefined reference" error doing this
`python configure.py --prob=$prob --coord=spherical_polar -mpi --flux=hllc --nghost=3 -hdf5 --hdf5_path=/usr/projects/hpcsoft/toss3/grizzly/hdf5/1.8.16_intel-17.0.4_intel-mpi-5.1.3 --cflag="-I/users/waterst3/local/libnoise/dist/include -L/users/waterst3/local/libnoise/dist/Release -lnoise"`

**Comment by trwaters** [comment]
And specifying LD_LIBRARY_PATH is the first thing I tried.  That works for a test driver, so I probably don't need the paths at all.  The feature to add `-lnoise` to `LDLIBS` in the Makefile would be great.

**Comment by tomidakn** [comment]
Ah, what if you keep `--include`?

**Comment by trwaters** [comment]
Doing 
`python configure.py --prob=$prob --coord=spherical_polar -mpi --flux=hllc --nghost=3 -hdf5 --hdf5_path=/usr/projects/hpcsoft/toss3/grizzly/hdf5/1.8.16_intel-17.0.4_intel-mpi-5.1.3 --include=/users/waterst3/local/libnoise/dist/include --cflag="-L/users/waterst3/local/libnoise/dist/Release -lnoise"`
gives me this, which still doesn't work
`Compilation command:     mpicxx  -I/usr/projects/hpcsoft/toss3/grizzly/hdf5/1.8.16_intel-17.0.4_intel-mpi-5.1.3/include -O3 -std=c++11 -L/users/waterst3/local/libnoise/dist/Release -lnoise -I/users/waterst3/local/libnoise/dist/include`

**Comment by tomidakn** [comment]
It seems that the ordering of the compiler options the configure script sets is not appropriate... `-I` has to come earlier.

**Comment by trwaters** [comment]
I see that now.  Thanks for the rapid responses!
