### ISSUE TITLE
Initialize problem generator with preexisting data from a file

### ISSUE THREAD

**Issue by trwaters** [PrincetonUniversity/athena-public-version#22]
Quoting from the docs on pgens: 
> The from_array problem generator (src/pgen/from_array.cpp) and associated input file (inputs/mhd/athinput.from_array) are designed to facilitate starting a simulation from initial values contained in a data file.

I need this capability.  Is it not available in the current public version?

**Comment by felker** [comment]
Will be released in `v1.2.0`, hopefully shortly.

**Comment by trwaters** [comment]
I see.  I just used the feature to change parameters using a new input file when relaunching a 1D run from a restart file - works beautifully!   Would it be possible to extend this feature to launch a 2D run from a 1D restart file?  I'm just wanting to run my 1D solutions in 2D now using the 1D solution as initial conditions, but I know the parallelization makes this complicated.

**Comment by c-white** [comment]
Going from 1D to 2D is the sort of thing that may introduce all sorts of corner cases we haven't considered - it would be hard to make this robust. The `from_array` methods to be released won't support this, but the release will have a convenient interface for reading HDF5 files from problem generators. This way you can read the 1D data and decide how to use it to initialize a 2D problem.

**Comment by trwaters** [comment]
Thanks, I figured.  The from_array methods sound great, I look forward to trying them out.
