### ISSUE TITLE
CUDA support

### ISSUE THREAD

**Issue by LeeJH** [PrincetonUniversity/athena-public-version#23]
Hi, 
   This project is working excellent with pure CPU, both MPI and OpenMP. But I am wondering whether CUDA support will be added to this project in the future, that we can enroll the GPU in computing.

**Comment by felker** [comment]
CUDA support will not be added to the project. For GPU support, I would suggest checking out https://gitlab.com/pgrete/kathena for a Kokkos-based fork of Athena++.
