### ISSUE TITLE
Corrupt HDF5 output when running across multiple nodes

### ISSUE THREAD

**Issue by michaeljennings11** [PrincetonUniversity/athena-public-version#30]
I am running a simulation on a cluster across multiple nodes with mpi and receiving corrupt hdf5 outputs (not recognizable by yt, hdfView, VisIt, etc.). Everything is fine of course when the simulation is run within a single node. Does Athena++ need to be specifically configured for runs across multiple nodes? Is this a known Athena issue that has been seen before, or just a user error on my part?

**Comment by felker** [comment]
You should make sure that your HDF5 library was compiled with MPI, since it is often compiled for only serial support. 

What error do you get with hdfView?

Currently, Athena++ HDF5 outputs can only be processed by VisIt via the XDMF plugin, so those files are what should be opened in VisIt, not the `.athdf` files

**Comment by michaeljennings11** [comment]
I am using the parallel HDF5 library. A more detailed explanation of the problem is the following:
The cluster I am using has nodes with 24 cores each. If I run a simulation in parallel with mpi and hdf5 outputs with 24 cores or less so it runs within one node everything works fine. I can load the athdf files with both yt and hdfView with no problem. If I run a simulation in parallel with mpi and hdf5  outputs with 64 cores so it runs across 3 nodes the output files are corrupt when trying to access through yt or hdfView. The hdfView error is "Failed to open file ...
java.io.IOException: Unsupported fileformat"

**Comment by felker** [comment]
It sounds to me that the most likely explanation is that your cluster's P-HDF5 library is broken. I cannot think of a reason why Athena++ itself would cause this behavior (although it is certainly possible). If you built it from source yourself, I believe that `make check` runs the HDF5 library tests. 

https://portal.hdfgroup.org/display/knowledge/The+parallel+tests+fail+on+a+login+node

I would also recommend loading a file with `h5py` to see what error it specifically throws.

**Comment by felker** [comment]
Were you able to test the P-HDF5 installation and/or install one from source?
