### ISSUE TITLE
Different levels of max refinement in different regions with AMR

### ISSUE THREAD

**Issue by TevaIlan** [PrincetonUniversity/athena-public-version#33]
Is there a way to set the maximum number of refinement levels to different values in different regions of the simulation? 

I'm running a simulation where I want a particular region to be more highly refined than any other part of the simulation but do to large changes in density, velocity, and pressure in other regions of the simulation, AMR always refines other regions to the maximum level of refinement. I want these other regions to be somewhat refined but not to the same level as the particular region that I want extremely refined. Does that make sense? Is there a way to do that?

**Comment by felker** [comment]
I believe that you could specify a [`RefinementCondition`](https://github.com/PrincetonUniversity/athena-public-version/wiki/Adaptive-Mesh-Refinement#the-amr-condition-refinementcondition) that internally checks the location of the MeshBlock and can `return 0` if it is in a region with a more conservative/hardcoded `numlevel_local` and it is at that level of refinement.
