### ISSUE TITLE
Memory leak using AMD Threadripper 2950x 

### ISSUE THREAD

**Issue by luminoctum** [PrincetonUniversity/athena-public-version#34]
Hi,

I compiled the most recent version of Athena++ using AMD threadripper 2950x CPU, gcc 9.2 and openmpi. I tried to test the field_loop_poles case using 16 cores in parallel. The test case is working properly but I found that my memory usage increases continuously at about 1GB per output step when the grid size is 64x32x128. It seems that this is the problem of the parallelization. The memory stays fine when I'm using single core. Do you have any idea of what may go wrong?

Thanks,
Cheng

**Comment by felker** [comment]
Sounds like a serious memory leak related to the parallel MPI I/O. If it is increasing by 1 GB per `dt_out`, does this not exhaust your memory before the end of the simulation? 

Which outputs (formats, quantities, dimensionality) are you dumping, and how often? Can you post your input file?

**Comment by luminoctum** [comment]
Yes, it exhausts my memory before it ends and then my system freezes. I'm using the standard input file athinput.field_loop_poles except that the mesh dimensions are increased to 64x32x128 and each meshblock is 32x16x32. The strange thing is that the model works fine when I compile it on an intel machine with openmpi. So, somehow, amd cpus and intel cpus behave differently using openmpi instructions. I'm trying other MPIs and other versions of gcc. I will keep you posted on the progress.

**Comment by felker** [comment]
Ok, so HDF5 is not used here. 

Can you try running the problem with `output1` disabled, then with `output2` disabled, then with both disabled and report the memory usage? 

https://github.com/PrincetonUniversity/athena-public-version/blob/d535095157c9b6dd67829dab4ce605d21da6efbb/inputs/mhd/athinput.field_loop_poles#L9-L16

**Comment by luminoctum** [comment]
Hi Felker,

An update. I haven't tried what you suggested. But I tried to use MPICH instead of openmpi which I have been using. It seems that the memory problem disappeared when I use MPICH. The exact reason is unknown but at least MPICH works for AMD CPUs now.

Cheng

**Comment by felker** [comment]
Could you quickly try the test I suggested with OpenMPI?
