### ISSUE TITLE
Possible error message typo in mesh.cpp

### ISSUE THREAD

**Issue by morganemacleod** [PrincetonUniversity/athena-public-version#38]
Hi folks, 

While incorrectly setting up an input file, I noticed that this error message on line ~331 of mesh.cpp might be incorrect:

          msg << "### FATAL ERROR in Mesh constructor" << std::endl
              << "Refinement level exceeds the maximum level (specify "
              << "'maxlevel' parameter in <mesh> input block if adaptive)."
              << std::endl;
          ATHENA_ERROR(msg);

(Should this read 'numlevel')?

Thanks! 

Morgan

**Comment by felker** [comment]
Thanks! Fixed upstream in private repo.
