### ISSUE TITLE
HDF5 outputs not readable by VisIt, Paraview, or yt

### ISSUE THREAD

**Issue by sddyates** [PrincetonUniversity/athena-public-version#4]
I've just been trying athena out using the double mach reflection AMR test. The hdf5 outputs that are generated appear corrupted in some way. 

Opening the files with yt just results in an error, VisIt hangs indefinitely and Paraview displays the results, but every block appears to be inverted (please see image below). 

This only seems to be affecting the hdf5 files as the static grid output in vtk format (for the orszag-tang test) is okay.

Is there some step in the configuration stage or an option in the input file which I'm missing?

Thanks for your help,
Simon

![screen shot 2017-04-25 at 12 26 36](https://cloud.githubusercontent.com/assets/8685312/25383202/ea726348-29b2-11e7-8adf-93f4d07ae79f.png)

**Comment by c-white** [comment]
I personally don't have experience with Paraview or YT, but I can comment on VisIt (2.12.0).

VisIt seems to be having trouble with some of our HDF5 files, in particular I think 2D files. This trouble amounts to taking a long time to first open a file, but it eventually gets the job done.

For concreteness, I ran the code as follows:

    ./configure --prob dmr -hdf5
    make clean
    make -j
    cd bin
    ./athena -i ../inputs/hydro/athinput.dmr_amr

I can then load the `amr.out1.*.athdf.xdmf` files with VisIt. However, it takes 5 minutes on my laptop for VisIt to make the first plot. After that, everything is fast, including moving the time slider, plotting new variables, and even closing and reopening the file.

Note, also, that VisIt has an issue with AMR when reading a group of files. If updating the time slider leads to a different number of blocks, one must reload the group.

Below is VisIt's pseudocolor plot for density in file number 20, with the outlines of the blocks overlayed (mesh plot with an index selection that has a stride of 16 in both i and j).

![amr](https://cloud.githubusercontent.com/assets/2496675/25551330/01b2716a-2c38-11e7-8362-be18834ccf38.png)

**Comment by jmshi** [comment]
I found similar problem with VisIt as posted by Simon.
Sometime all the meshblocks in the hdf5 data do not
seem to be arranged correctly in VisIt viewer when
multiple processes are used to open the data.
I have to choose serial instead of parallel to get the correct image.
The problem seems to be related to the default reader in VisIt (Xdmf?)
when works in parallel..

JM

**Comment by sddyates** [comment]
Thanks both of you for your suggestions. I re-tried with VisIt and was more patient this time and eventually it loaded the data. VisIt appears to think the data is 3D rather than 2D. I've checked the outputs from the dmr AMR test and I get exactly the same results as you c-white.

I haven't encountered the same problem as you have described JM, for the multi-threaded VisIt. This may be due to it not being activated in my version. How do you turn this on or off?

Cheers,
Simon
