### ISSUE TITLE
Get the number of cells during run-time

### ISSUE THREAD

**Issue by zengbs** [PrincetonUniversity/athena-public-version#41]
Dear Athena++ developers,
If dumping data on disk is not allowed, is it possible to obtain the following numbers during simulation of special relativistic hydrodynamics with AMR? 
1) the total number of non-ghost cells inside box + number of ghost cells
2) the total number of non-ghost cells inside box
best,
Po-Hsun Tseng (Rocky)

**Comment by tomidakn** [comment]
Mesh::nbtotal is an integer holding the total number of MeshBlocks, and is public. So you can simply multiply the number of cells per MeshBlock (which you can calculate using either MeshBlock::block_size or MeshBlock::is,ie,js,je,ks,ke) and this number to get the total number of active cells. Also, you can calculate the number of ghost cells in each MeshBlock using NGHOST, which is a global constant.
