### ISSUE TITLE
Incomplete docs or problem with Keplerian disk example

### ISSUE THREAD

**Issue by emprice** [PrincetonUniversity/athena-public-version#42]
The cylindrical Keplerian disk example says to configure with:

```
python configure.py --prob=disk --coord=cylindrical
```

However, when I do this, and then `make` and run `bin/athena -i inputs/hydro/athinput.disk_cyl`, I get an error that the `GM` parameter only works in spherical polar or 2d cylindrical coordinates. I guess maybe the example is supposed to be run in 2d? But if that is the case, I haven't found an option to turn that on.

Any help with this issue is appreciated. I'm sure the solution is simple, but as a complete novice coming to Athena++, I just haven't been able to figure it out.

**Comment by beresnyak** [comment]
Apparently it says you can't have "z" dimension (height) - nx3 must be 1.

**Comment by felker** [comment]
@beresnyak is correct: `bin/athena -i inputs/hydro/athinput.disk_cyl mesh/nx3=1`  does run successfully. 

If you want a 3D simulation with the point mass source, you can rebuild the solver with  `--coord=spherical_polar`.
