### ISSUE TITLE
Implementation of time-implicit method in problem generator 

### ISSUE THREAD

**Issue by doraemonho** [PrincetonUniversity/athena-public-version#48]
Hello,

   I am trying to write a time-implicit and sub-cycle cooling solver in the problem generator. Following the instruction in the wiki, it recommends the user to write the solver in the `MeshBlock::UserWorkInLoop`.  I have a few questions about the implementation. 

1. What is the right way to get the thermal pressure value inside the code? I see the example of the explicit method inside the wiki using `Real temp = (g-1.0)*prim(IEN,k,j,i)/prim(IDN,k,j,i);`  to get the temperature and it seems that the kinetic energy and magnetic energy are already subtracted from the internal energy before the Athena is calling the `EnrollUserExplicitSourceFunction` function. However, the internal energy term `phydro->u(IEN,k,j,i)` in the `UserWorkInLoop`  seems to include the K.E and M.E. 

2. What is the right way to update the thermal pressure?  I see two objects is related to the thermal pressure, one is `phydro->u(IEN,k,j,i)` and another is `phydro->w(IPR,k,j,i)`. Should I update both of them or just one?

**Comment by rcdannen** [comment]
Hi,

1.  That seems to be the case.  In order to get temperature when you only have access to the conserved variables (not the primitives like in the example you showed) you need to subtract the kinetic energy and magnetic energy.

2.  We've found the most straightforward way to include heating and cooling in our models is to use the method of enrolling a user source term described on the [problem generator page of the wiki](https://github.com/PrincetonUniversity/athena-public-version/wiki/Problem-Generators).  I'll go over our specific implementation.  First, we enroll the user source term when we initialize our mesh data.

```
void Mesh::InitUserMeshData(ParameterInput *pin) {
  /* more code */
  EnrollUserExplicitSourceFunction(TotalSrcTerm);
  /* more code */
  return;
}
```
where the `TotalSrcTerm` contains all of our source terms, but I'll just include heating and cooling in this example.    We also first define a user mechblock to hold the heating and cooling information for us, and you can of course add more to hold other important variables.

```
void MeshBlock::InitUserMeshBlockData(ParameterInput *pin)
{
  // array to hold the heating and cooling data
  AllocateRealUserMeshBlockDataField(0);
  ruser_meshblock_data[0].NewAthenaArray((ke-ks)+2*NGHOST,(je-js)+2*NGHOST,(ie-is)+2*NGHOST); 

  for(int k=ks; k<=ke; ++k) { 
    for (int j=js; j<=je; ++j) {
      for (int i=is; i<=ie; ++i) {
        ruser_meshblock_data[0](k,j,i) = 0.; // initialize to 0.
      }
    }
  }
  return;
}
```
We have a function that calculates the heating and cooling for each grid point and storing it in the data structure we defined prebiously.
```
void HeatingCoolingSrcTerm(MeshBlock *pmb, const Real time, const Real dt, const AthenaArray<Real> &prim, 
                           const AthenaArray<Real> &bcc, AthenaArray<Real> &cons) {

  // Iterate over all points in domain 
  for (int k=pmb->ks; k<=pmb->ke; ++k) {
    for (int j=pmb->js; j<=pmb->je; ++j) {
      for (int i=pmb->is; i<=pmb->ie; ++i) {

        Real net_hc_rate;
        Real rho = prim(IDN,k,j,i);  
        Real   P = prim(IEN,k,j,i);
        Real   T = (g - 1.) * P / rho;
        /* use that information to calculate the net heating/cooling rate */
        pmb->ruser_meshblock_data[0](k,j,i) = net_hc_rate; // store H/C in Athena Array 
      }
    }
  }
}

```
And we have our total source term function that incorporates our source term. 
```
void TotalSrcTerm(MeshBlock *pmb, const Real time, const Real dt, const AthenaArray<Real> &prim,
                      const AthenaArray<Real> &bcc, AthenaArray<Real> &cons) {
  
  HeatingCoolingSrcTerm(pmb,time,dt,prim,bcc,cons);
  /* Update Energy */
  for (int k=pmb->ks; k<=pmb->ke; ++k) {
    for (int j=pmb->js; j<=pmb->je; ++j) {
      for (int i=pmb->is; i<=pmb->ie; ++i) {
        // update energy with the value stored in the user meshblock
        cons(IEN,k,j,i) += dt*pmb->ruser_meshblock_data[0](k,j,i);
      }
    }
  }
}
```
You can skip defining a separate function for the heating and cooling and just do this all in the total source term, but for this set ups allows for easier addition of more source terms.  You notice for our source term, we pass the array that holds the primitive values, so we can calculate temperature more directly.

**Comment by doraemonho** [comment]
Hi,

  Thank you for the clear explanation! 

I just get one more question about that. Since the cooling time scale is too small in my model, it would be very computationally expensive for me to apply the time explicit method. Could I switch the calculation from `TotalSrcTerm` to a semi-implicit/fully implicit method? (The implicit method would be like applying the Newton–Raphson iteration and sub-cycling until it finds the solution, like [here (Kim & Basu 2013 ,in the end of page 2)](https://iopscience.iop.org/article/10.1088/0004-637X/778/2/88/pdf) I see from wiki pointing out that the implicit integrator does not work well inside the `EnrollUserExplicitSourceFunction` and doesn't encourage the user to do the implicit integration inside this function.

**Comment by c-white** [comment]
Just chiming in that the wiki conflicts with itself on this point. I see the [Problem Generators](https://github.com/PrincetonUniversity/athena-public-version/wiki/Problem-Generators) page says about `EnrollUserExplicitSourceFunction`

> Note that this feature is designed for time-explicit integration, and does not work well with any time-implicit or sub-cycling method. If you need these integrators, you have to implement the integrator for yourself in the `MeshBlock::UserWorkInLoop` function.

On the other hand, for `MeshBlock::UserWorkInLoop` it says

> This is intended only for analysis, and not for manipulating the data.

Manipulating the data is safest with enrolling an explicit source function. This function is called at the end of every substep in the time integration. Its intention is to update the conserved variable array in the function input, which has already been updated according to the flux divergence for the substep. If you are imposing some constraint (e.g. a temperature ceiling) or doing something implicit, you should ignore the primitive input and deal only with the conserved values. If you are adding a proper physical source (e.g. explicit cooling) you should calculate the conserved change from the not-yet-updated primitive input and apply it to the conserved values. After this function is called, the code performs conserved-to-primitive inversion to update the primitives to agree with the conserved values.

`MeshBlock::UserWorkInLoop`, on the other hand, is only called at the end of the full timestep. This makes it well situated if you want to do something fully operator split from the hydrodynamics (as opposed to the semi-split explicit source function). However, this can be a bit unsafe. In particular, this function is called *after* the last conserved-to-primitive call, so *if* the user changes variables here, the change must be done consistently to both the primitives and conserved variables. Moreover, the function is called *after* the boundary functions, so the user must update the ghost cells (both internal and external) here to reflect what the boundary functions would have done had they been given the updated state.

We should probably remove the recommendation to use `MeshBlock::UserWorkInLoop` for anything other than passive analysis, given the chance of doing something unphysical. I don't use implicit cooling myself, but do the other devs know what could go wrong doing this every substep anyway, besides just a cost that scales with the number of integration stages?

**Comment by c-white** [comment]
@doraemonho To address your questions about energy, `phydro->w` is the primitives, consisting of density (`IDN`), gas pressure (`IPR`, not internal or any other energy), and velocity (`IVX`, `IVY`, `IVZ`). `phydro->u` is the conserved variables, consisting of density (`IDN`, same density as before for Newtonian physics), total kinetic + internal + magnetic energy (`IEN`), and momentum (`IM1`, `IM2`, `IM3`).

Old versions of the code used `IEN` for both energy (when dealing with `u`) and pressure (when dealing with `w`), but we added `IPR` to emphasize that these elements are pressures not energies. `IEN` and `IPR` expand to the same thing (the integer 4, if you were wondering), so everything works by using `phydro->w(IEN,...)` to index pressure, but it gets confusing and we still need to remove a few lingering instances of this in the code base.

**Comment by c-white** [comment]
@rcdannen It's never a bad idea to zero arrays yourself if you want them to be zero, but I thought I'd point out that `NewAthenaArray` always creates a zero-initialized array.

**Comment by lucyundead** [comment]
I have tried with a time explicit cooling source term in athena++, and it is indeed very computationally expensive (even for a 2D case).  It might be worth trying to use Grackle package for your problem with cooling and chemisity (https://grackle.readthedocs.io/en/latest/).

**Comment by munan** [comment]
I already implemented chemistry and cooling (for atomic and diffuse
molecular ISM) in a private branch in Athena++:
https://github.com/PrincetonUniversity/athena/wiki/chemistry
The chemistry and internal energy are updated with an implicit ODE solver
in the operator split manner.

I haven't finished all the testing and it's not in the public version yet.
But if this is what you want to do, let me know and perhaps we can avoid
some repetitive work.

**Comment by trwaters** [comment]
@munan - excited to hear your work adding a chemistry network is almost finished!

@doraemonho, the procedure outlined by @rcdannen can be used for an explicit or semi-implicit update of a basic heating/cooling function.  To do a semi-implicit solve, within the loops of his
`HeatingCoolingSrcTerm()` you would have, for example,
` T_new = call_rootfinder(dt,rho,T);`
`net_hc_rate = get_hc_rate(rho,T_new);`
before the line
`pmb->ruser_meshblock_data[0](k,j,i) = net_hc_rate;`

If you have access to a cluster, we have had good luck with an explicit solve even for stiff cooling functions upon implementing a user-defined timestep (see the _Problem Generator_ section of the wiki).

**Comment by rcdannen** [comment]
> @rcdannen It's never a bad idea to zero arrays yourself if you want them to be zero, but I thought I'd point out that `NewAthenaArray` always creates a zero-initialized array.

Good to know, I think that was a case of being overly cautious on my end.  Thank you for your replies, you've inspired some changes to how we are implementing heating and cooling.

**Comment by felker** [comment]
> It's never a bad idea to zero arrays yourself if you want them to be zero, but I thought I'd point out that `NewAthenaArray` always creates a zero-initialized array.

It might be a bad idea if you want optimal performance.

https://github.com/PrincetonUniversity/athena-public-version/blob/d535095157c9b6dd67829dab4ce605d21da6efbb/src/athena_arrays.hpp#L369

FYI, the presence of the `()` zero-initializes the array in C++: 
https://stackoverflow.com/questions/2204176/how-to-initialise-memory-with-new-operator-in-c

**Comment by doraemonho** [comment]
@c-white  Thanks for the clarification! I noticed the boundary issue yesterday when I changed variables in the  `MeshBlock::UserWorkInLoop`.  I try to write the below iteration to update all the cells. Is this a correct way to visit all the cells inside the function?

```
  for (int k=ks-NGHOST; k<=ke+NGHOST; ++k) {  
    for (int j=js-NGHOST; j<=je+NGHOST; ++j) {  
#pragma omp simd  
      for (int i=is-NGHOST; i<=ie+NGHOST; ++i) {  
        Real n    = phydro->w(IDN,k,j,I);  
        Real e    = phydro->w(IPR,k,j,i)/(g-1.0);  
        Real de  =  CoolingFunction(e,n,g,my_dt);  //Calcualate the cooling here  
        phydro->u(IEN,k,j,i) += de;  
        phydro->w(IPR,k,j,i) += de*(g-1.0);  
      }
    }
  }
```

@munan I am working on a similar problem but with a simple cooling function ( CII + Ly-alpha) combined with the turbulence driving right now. Excited to hear the similar work is already finished! I am glad if I can contribute to the development of Athena. 

@trwaters So far I am testing my integrator in the single node AMD machine yet but I would migrate the testing to cluster once I overcome the numerical instability. I am wondering would the performance drops a lot in the multi-node environment?

**Comment by trwaters** [comment]
@doraemonho, Athena++ scales very well.  See Section 3.6 of [the methods paper](https://arxiv.org/abs/2005.06651).
