### ISSUE TITLE
simultaneous AMR and SMR

### ISSUE THREAD

**Issue by Yotag** [PrincetonUniversity/athena-public-version#49]
I have seen an old page in the wiki that states that AMR and SMR can be used together :
"remove the <refinement1> block as it is not needed any more
if the block is still present, the solver will apply this SMR 
 and refine further if prompted by the AMR refinement condition"

How I am trying to run it now with V 1.1.0 and it seems to just ignore the AMR call.
Am I doing something wrong or is the option just not available?
Regards,
Yotam.

**Comment by felker** [comment]
It should work, but it is impossible to tell if you are using it correctly without specifying your input file and problem generator.

**Comment by Yotag** [comment]
The problem generator is one I costume made.
AMR works for me, SMR works for me.
but trying to add this into the input file:

refinement = adaptive
numlevel = 5
deref_count = 5 

<refinement1>
x1min=-13000
x1max= 13000
x2min=-13000
x2max= 13000
x3min=-13000
x3max= 13000
level=3

he just ignores the AMR command. Even though if I put 
numlevel = 2 
for adaptive I get the error messege 
"### FATAL ERROR in Mesh constructor
Refinement level exceeds the maximum level (specifymaxlevel in <mesh> if adaptive)."

If this is not enough info I will try to reproduce my issue using a default problem generator.

Thanks for the support.

**Comment by felker** [comment]
You get that error in the latter case because `level=3` SMR exceeds the maximum allowed refinement level `numlevel=2`.

AMR might be ignored in the former case because your `RefinementCondition` is not sufficiently sensitive for your purposes.

**Comment by Yotag** [comment]
I managed to run AMR and SMR simultaneously on a default problem generator. It looks like the problem was in my own code. Thanks for the replies!

I opened the issue in the first place because I was unsure if you can still run them both in current versions,  as it is no longer explicitly specified in the wiki like it used to be. 
Perhaps it is possible to add a clarification to the current wiki page?

Have a pleasant weekend.
