### ISSUE TITLE
Magnetic fields without MHD solver

### ISSUE THREAD

**Issue by michaeljennings11** [PrincetonUniversity/athena-public-version#51]
Hello All,

I was wondering if there is a straightforward way to include magnetic fields but turn off the MHD solver. I am interested in testing a new physics module that requires the magnetic field direction but I don't want to solve the MHD equations (basically I want to initialize a static uniform magnetic field that wont interact with the fluid).

Any insight is much appreciated!

Best,
Michael

**Comment by felker** [comment]
If I recall correctly, you could disable the contents of: 
https://github.com/PrincetonUniversity/athena-public-version/blob/d535095157c9b6dd67829dab4ce605d21da6efbb/src/task_list/time_integrator.cpp#L786

Your mileage may vary if you are using mesh refinement, etc.

**Comment by michaeljennings11** [comment]
Great, thank you! I'll give this a try.
