### ISSUE TITLE
Comet Virtual Method Error

### ISSUE THREAD

**Issue by smressle** [PrincetonUniversity/athena-public-version#55]
Hi all, 

Has anyone run into problems running athena++ on SDSC's Comet?  When compiled with their intel compiler ( intel 2018.1.163) the code crashes after initialization with the following error:

pure virtual method called
terminate called without an active exception

It seems that this happens for any input file and configuration with the unedited public version.  When compiled with gcc the code runs fine.  Strangely, when using the same intel 2018.1.163 compiler on a different cluster the code also runs fine, so this seems to be a Comet-specific problem.  Also, the previous version of the code works well on Comet.

**Comment by felker** [comment]
Known problem with certain Intel compilers from 2017 (and I guess early 2018) that affect versions of Athena++ after I rewrote the boundary values classes and added passive scalars. @tomidakn and I were the only ones to encounter it, I believe.

**Comment by smressle** [comment]
Is there a work around?

**Comment by felker** [comment]
No. Newer Intel compiler.

**Comment by trwaters** [comment]
Right, I hit this last year ([#29](https://github.com/PrincetonUniversity/athena-public-version/issues/29)) with Intel v18 and there was no issue with Intel v19.

**Comment by smressle** [comment]
Got it, thanks.  I'll probably just transfer the comet time since they only
have the one version.
