### ISSUE TITLE
Code doesn't recognize <meshblock> input block in athinput file

### ISSUE THREAD

**Issue by Yotag** [PrincetonUniversity/athena-public-version#6]
I am trying to run a parallel simulation using mpi.
I have included <meshblock> in the input file but the code seems to not see it, I get an error 
"Too few mesh blocks nbtotal(1) <nrank(8)"
Is there anything else that needs to be done in order to register the number of blocks?
Thanks in advance

**Comment by tomidakn** [comment]
Hi,

Currently our input file reader does not recognize "tab". So if you use tabs for spacing, please replace them with spaces. If this does not work, please let us know.

Kengo

**Comment by Yotag** [comment]
hi, that fixed it! thanks alot.
