### ISSUE TITLE
Vacuum Boundary Conditions for Self Gravity

### ISSUE THREAD

**Issue by michaeljennings11** [PrincetonUniversity/athena-public-version#60]
I need to implement boundary conditions for the gravitational potential in the following manner: shearing-periodic in x, periodic in y, and vacuum in z. Is this currently possible in the public version of Athena++?

In the documentation for "Self Gravity with FFT" it says other boundary conditions other than periodic are not yet implemented. Is this possible with multigrid? The documentation page for "Self-Gravity with Multigrid" is non-existent so I am unsure how to even enroll it in Athena++.

**Comment by changgoo** [comment]
It is not available in the public version of Athena++ (nor in the development version officially). I think various people have their own version for that though. Athena C-version has an FFT gravity solver with the boundary conditions you wish to use (https://github.com/PrincetonUniversity/Athena-Cversion/blob/master/src/gravity/selfg_fft_disk.c). We are working on it (with some improvements), but will not be immediately available in the public version.

**Comment by changgoo** [comment]
The multigrid solver is under development and not available in the public version yet.

**Comment by michaeljennings11** [comment]
Thank you for your help!

Michael
