### ISSUE TITLE
Passive scalar issue

### ISSUE THREAD

**Issue by jmpittard** [PrincetonUniversity/athena-public-version#62]
Dear all,

I am trying to simulate a 1D spherically symmetric wind-blown-bubble and I have included a passive scalar which has a value of 1.0 for the wind and 0.0 for the surrounding uniform ambient medium. I overwrite values within a "remap radius" so that the wind keeps blowing. I find that the scalar values inside the remap region take undesirable values and that the scalar value in the wind increases above a value of 1.0. This can be easily checked by looking directly at the 1D values in the *.tab output.

The issue is a basic one because I am not doing anything fancy (e.g. AMR etc). There doesn't seem to be a similar issue in the database. My guess is that the user-enrolled source function is not designed to be used in the way that I am doing so...

I have pasted the pgen and athinput files below. I configure with:

python configure.py --prob wbbJMP --coord spherical_polar --nscalars 1

and run with:

athena -i athinput.wbb_1D_RTP

Any insight on this would be most welcome.

Thank you,
Julian

//========================================================================================
// Athena++ astrophysical MHD code
// Copyright(C) 2014 James M. Stone <jmstone@princeton.edu> and other code contributors
// Licensed under the 3-clause BSD License, see LICENSE file for details
//========================================================================================
//! \file wbbJMP.cpp
//  \brief Problem generator for WBB problem (JMP)
//
// The WBB problem consists of a supersonic wind blowing into the ISM.
// Input parameters are:
//    - problem/mdot  = mass-loss rate of the star (Msol/yr)
//    - problem/vinf  = terminal wind speed of the star (cm/s)
//    - problem/xpos  = coordinate-1 position of the star (cm)
//    - problem/ypos  = coordinate-2 position of the star (cm)
//    - problem/zpos  = coordinate-3 position of the star (cm)
//    - problem/rhoamb= density of ambient medium (g/cm3)
//    - problem/Tamb  = temperature of ambient medium (K)
//
// Wind "colour" uses the first advected scalar (index 0).
//
//========================================================================================

// C headers

// C++ headers
#include <cmath>      // sqrt()
#include <fstream>
#include <iostream>   // endl
#include <sstream>    // stringstream
#include <stdexcept>  // runtime_error
#include <string>     // c_str()

// Athena++ headers
#include "../athena.hpp"
#include "../athena_arrays.hpp"
#include "../bvals/bvals.hpp"
#include "../coordinates/coordinates.hpp"
#include "../eos/eos.hpp"
#include "../field/field.hpp"
#include "../globals.hpp"
#include "../hydro/hydro.hpp"
#include "../mesh/mesh.hpp"
#include "../parameter_input.hpp"
#include "../scalars/scalars.hpp"   // JMP: needed for scalars

Real gmma1;
Real mdot, vinf;
Real xpos, ypos, zpos;
Real rhoamb, Tamb;
Real tmin,tmax;

// Physical and mathematical constants
const Real pi = 2.0*asin(1.0);
const Real Msol = 1.9891e33;
const Real yr = 3.15569e7;
const Real boltzman = 1.380658e-16;
const Real massh = 1.67e-24;

// User defined constants
const Real Twind = 1.0e4;                                // K

// JMP prototypes
void RemapWind(MeshBlock *pmb, const Real time, const Real dt, const AthenaArray<Real> &prim,
                  const AthenaArray<Real> &bcc, AthenaArray<Real> &cons);

//========================================================================================
//! \fn void Mesh::InitUserMeshData(ParameterInput *pin)
//  \brief Function to initialize problem-specific data in mesh class.  Can also be used
//  to initialize variables which are global to (and therefore can be passed to) other
//  functions in this file.  Called in Mesh constructor.
//========================================================================================

void Mesh::InitUserMeshData(ParameterInput *pin) {

  mdot = pin->GetReal("problem","mdot");
  vinf = pin->GetReal("problem","vinf");
  xpos = pin->GetReal("problem","xpos");
  ypos = pin->GetReal("problem","ypos");
  zpos = pin->GetReal("problem","zpos");
  rhoamb = pin->GetReal("problem","rhoamb");
  Tamb   = pin->GetReal("problem","tamb");
  
  mdot *= Msol/yr;

  // Note: it is only possible to have one source functions enrolled by the user.
  EnrollUserExplicitSourceFunction(RemapWind);

  return;
}

//========================================================================================
//! \fn void MeshBlock::ProblemGenerator(ParameterInput *pin)
//  \brief Problem Generator for the WBB test
//========================================================================================

void MeshBlock::ProblemGenerator(ParameterInput *pin) {
  Real gmma  = peos->GetGamma();
  gmma1 = gmma - 1.0;

  Real avgmass = 1.0e-24;     // g

  int remapi = 10;
  Real dx = pcoord->dx1v(0);
  Real remap_radius = Real(remapi)*dx;
  
  // Map on ambient gas
  for (int k=ks; k<=ke; k++) {
    for (int j=js; j<=je; j++) {
      for (int i=is; i<=ie; i++) {
	phydro->u(IDN,k,j,i) = rhoamb;
        phydro->u(IM1,k,j,i) = 0.0;
	phydro->u(IM2,k,j,i) = 0.0;
	phydro->u(IM3,k,j,i) = 0.0;
	Real pre = (rhoamb/avgmass)*boltzman*Tamb;
        phydro->u(IEN,k,j,i) = pre/gmma1;
	if (NSCALARS > 0) {
          pscalars->s(0,k,j,i) = 0.0;
        }
      }
    }
  }

  
  // Map on wind out to a particular radius. Overwrite ambient gas.
  if (std::strcmp(COORDINATE_SYSTEM, "spherical_polar") == 0) { // RTP. ie. x = R; y = theta; z = phi
    for (int k=ks; k<=ke; k++) {
      for (int j=js; j<=je; j++) {
        for (int i=is; i<=ie; i++) {
  	  Real r = pcoord->x1v(i);
	  if (r <= remap_radius){
	    Real rho = mdot/(4.0*pi*r*r*vinf);
	    Real u1 = vinf;
	    Real u2 = 0.0;
	    Real u3 = 0.0;
	    Real pre = (rho/avgmass)*boltzman*Twind;
	    phydro->u(IDN,k,j,i) = rho;
            phydro->u(IM1,k,j,i) = rho*u1;
            phydro->u(IM2,k,j,i) = rho*u2;
            phydro->u(IM3,k,j,i) = rho*u3;
            phydro->u(IEN,k,j,i) = pre/gmma1 + 0.5*rho*(u1*u1 + u2*u2 + u3*u3);
	    if (NSCALARS > 0) {
              pscalars->s(0,k,j,i) = rho;
            }
          } 
	} 
      }
    }
  }  
  
  return;
}

//========================================================================================
//! \fn void MeshBlock::RemapWind(MeshBlock *pmb, const Real time, const Real dt, const AthenaArray<Real> &prim,
//		const AthenaArray<Real> &bcc, AthenaArray<Real> &cons)
//  \brief Remap wind
//  NOTE: JMP 11/08/20 - The wind passive scalar is not accurately treated for some reason...
//========================================================================================
void RemapWind(MeshBlock *pmb, const Real time, const Real dt, const AthenaArray<Real> &prim,
		const AthenaArray<Real> &bcc, AthenaArray<Real> &cons){

  Real g = pmb->peos->GetGamma();
  gmma1 = g - 1.0;

  Real avgmass = 1.0e-24;     // g
  
  int remapi = 10;
  Real dx = pmb->pcoord->dx1v(0);
  Real remap_radius = Real(remapi)*dx;

  if (std::strcmp(COORDINATE_SYSTEM, "spherical_polar") == 0) { // RTP. ie. x = R; y = theta; z = phi
    for (int k=pmb->ks; k<=pmb->ke; ++k) {
      for (int j=pmb->js; j<=pmb->je; ++j) {
        for (int i=pmb->is; i<=pmb->ie; ++i) {
  	  Real r = pmb->pcoord->x1v(i);
	  if (r <= remap_radius){
	    Real rho = mdot/(4.0*pi*r*r*vinf);
	    Real u1 = vinf;
	    Real u2 = 0.0;
	    Real u3 = 0.0;
	    Real pre = (rho/avgmass)*boltzman*Twind;
	    cons(IDN,k,j,i) = rho;
            cons(IM1,k,j,i) = rho*u1;
            cons(IM2,k,j,i) = rho*u2;
            cons(IM3,k,j,i) = rho*u3;
            cons(IEN,k,j,i) = pre/gmma1 + 0.5*rho*(u1*u1 + u2*u2 + u3*u3);
	    if (NSCALARS > 0) {
              pmb->pscalars->s(0,k,j,i) = rho;
            }
	  } // r < remap_radius
	}
      }
    }
  }  
  return;
}

athinput.wbb_1D_RTP:

#Spherical WBB problem
<comment>
problem   = WBB
reference = Pittard
configure = --prob=wbbJMP

<job>
problem_id = wbb_1drtp  # problem ID: basename of output filenames

<output1>
file_type  = hst        # History data dump
dt         = 1.0e9      # time increment between outputs (s)

<output2>
file_type  = tab        # formatted table data dump
variable   = prim       # variables to be output
data_format = %12.5e    # Optional data format string
id         = prim       # identifier in filename
dt         = 1.0e9      # time increment between outputs
x2_slice    = 0.0       # slice in x2
x3_slice    = 0.0       # slice in x3

<time>
cfl_number = 0.4        # The Courant, Friedrichs, & Lewy (CFL) Number
nlim       = 100000000  # cycle limit
tlim       = 1.0e10     # time limit
integrator  = vl2       # time integration algorithm
xorder      = 2         # order of spatial reconstruction
ncycle_out  = 1         # interval for stdout summary info

<mesh>
nx1        = 80         # Number of zones in X1-direction
x1min      = 0.0e18     # minimum value of X1
x1max      = 2.0e18     # maximum value of X1
ix1_bc     = reflecting # inner-X1 boundary flag
ox1_bc     = outflow    # outer-X1 boundary flag

nx2        = 1          # Number of zones in X2-direction
x2min      = 0.0        # minimum value of X2
x2max      = 1.0        # maximum value of X2
ix2_bc     = outflow    # inner-X2 boundary flag
ox2_bc     = outflow    # outer-X2 boundary flag

nx3        = 1          # Number of zones in X3-direction
x3min      = 0.0        # minimum value of X3
x3max      = 1.0        # maximum value of X3
ix3_bc     = outflow    # inner-X3 boundary flag 
ox3_bc     = outflow    # outer-X3 boundary flag

<hydro>
gamma      = 1.66667    # gamma = C_p/C_v
dfloor     = 1.0e-30    # required otherwise Athena++ uses a default value
pfloor     = 1.0e-30    # required otherwise Athena++ uses a default value
sfloor     = 0.0

<problem>
mdot      = 4.0e-6     # Mass-loss rate of the star (Msol/yr)
vinf      = 2.0e8      # Terminal wind speed of the star (cm/s)
xpos      = 0.0        # Coordinate-1 position of the star (cm)
ypos      = 0.0        # Coordinate-2 position of the star (cm)
zpos      = 0.0        # Coordinate-3 position of the star (cm)
rhoamb    = 1.0e-24    # ambient density of ISM (g/cm^3)
tamb      = 1.0e4      # ambient temperature of ISM (K)

**Comment by jmpittard** [comment]
The formatting of the athinput file was not preserved so I've attached it and the pgen file below:

[wbbJMP.cpp.TXT](https://github.com/PrincetonUniversity/athena-public-version/files/5220018/wbbJMP.cpp.TXT)

[athinput.wbb_1D_RTP.TXT](https://github.com/PrincetonUniversity/athena-public-version/files/5220006/athinput.wbb_1D_RTP.TXT)

**Comment by felker** [comment]
Yeah, this isnt how a source function should be used. It is kind of "cheating" to modify the the conserved passive scalar mass by going through the `MeshBlock` class within a user-defined hydro source term function; you are really only meant to apply **hydrodynamic** source terms via the explicitly passed function arguments.  See `constant_acc.cpp`, for example. 

The reason the scalar values inside the remap region exceed 1.0 is that the `INT_SCLR` step occurs **after** the `SRCTERM_HYD` step in the task list (see `time_integrator.cpp`). So for each time integrator stage, you reset the conserved `s` to 1.0, but then apply the flux divergence update to the scalars based on the previously computed passive scalar fluxes. 

Maybe applying the remap in either `UserWorkAfterLoop` or `UserWorkInLoop` would work

**Comment by jmpittard** [comment]
Yes, it works if it is applied in `UserWorkInLoop`. Thanks!

**Comment by c-white** [comment]
@jmpittard The next public release will add arguments to the user-defined source term function signature, so that you can (and should) modify the scalars there.

**Comment by felker** [comment]
@c-white however @jmpittard should still implement his "reset" approach in `UserWorkInLoop`, since it cannot be properly treated as a source term due to my explanation above.
