### ISSUE TITLE
Implementing a 'locally isothermal' EoS

### ISSUE THREAD

**Issue by ncimerman** [PrincetonUniversity/athena-public-version#64]
Dear all,

I am currently using Athena++ for some simulations of disc-planet interactions. So far, I have used a (globally) isothermal EoS, such that the sound-speed c_s = const, which is barotropic.

Now I would like to explore some effects of using a different, non-barotropic EoS, in particular one where the sound-speed is a function of cylindrical radius in the disc c_s = c_s(R), often referred to as 'locally isothermal'.

I have looked into the code and how EoSs are implemented, but I'm not entirely sure if I would have to make changes to the Riemann solvers themselves as well.

I do remember some people using an adiabatic EoS, with \gamma close to unity and a cooling term that takes the sound-speed back to its unperturbed value, but it seems that this would require more operations than just prescribing a different sound-speed.

Thus, I was wondering if someone has some experience with implementing such an equation of state and if there is perhaps a simpler way to do it.

Any help would be much appreciated.

Thanks and Kind Regards,
Nicolas

**Comment by msbc** [comment]
Hi Nicolas,

The current implementation of the Riemann solvers (and all EOS calls) assume no explicit coordinate dependance. While the sound-speed (an EOS function) is used in the Riemann solver, it's also used to compute the hydro time step.

**Comment by trwaters** [comment]
Hi Nicolas,

Locally isothermal is a standard approximation in MHD wind studies.  See for example this recent paper using Athena++
https://ui.adsabs.harvard.edu/abs/2018ApJ...857...34Z/abstract
in particular footnote 4 shows how they achieve it.

**Comment by ncimerman** [comment]
Hi all,

thanks for the very quick responses, I hope you are all doing well in these 'interesting' times!

This does indeed sound like a beta-cooling with the cooling time-scale beta -> 0, so it becomes instantaneous. I was playing with the idea of implementing some beta-cooling in adiabatic simulations anyway, so I think I will give that a go.

That means I should get away with only modifying my problem-generator, rather than changing the functions in the EoS class and the calls all over the code.

Thanks again,
Nicolas
