### ISSUE TITLE
NSCALARS>2 With Polar Boundary Error

### ISSUE THREAD

**Issue by smressle** [PrincetonUniversity/athena-public-version#66]
The array flip_across_pole_hydro = {false, false, true, true, false} is used for both the hydro variables and the scalar variables in polarwedge_cc.cpp.  This means that the n=2 and n=3 scalars will be negative in some of the boundary cells.  Furthermore, if n> 5 there will presumably be a memory error calling the flip_across_pole_hydro array.

**Comment by felker** [comment]
Good catch; should be an easy fix. Did you run into this problem in a simulation with many species of scalars?

**Comment by smressle** [comment]
Yeah I was just running some test problems where I had multiple electron entropies acting as passive scalars.  Negative entropy resulting in nan internal energy when inverting which led to me finding the issue.  Thankfully I will be using cartesian coordinates for the actual production simulations I am interested in.

**Comment by c-white** [comment]
I'm guessing `polarwedge_cc.cpp` should be inspecting the class member `flip_across_pole_` rather than the global `flip_across_pole_hydro`, only using it if it is not `nullptr` like in `bvals_cc.cpp`?

**Comment by felker** [comment]
I believe I have fixed this. Let me know if it doesnt work, @smressle

**Comment by smressle** [comment]
Great, thanks Kyle!  I'll give it a shot.
