### ISSUE TITLE
Starting value for maximzed user defined history outputs

### ISSUE THREAD

**Issue by forrestglines** [PrincetonUniversity/athena-public-version#67]
I stumbled upon this bug in `history.cpp` when using a user defined history output with `UserHistoryOperation::max`. The starting value for the reduction seems incorrect

https://github.com/PrincetonUniversity/athena-public-version/blob/4fc45f9d04861471ce9ebc6ced66da87a00beac3/src/outputs/history.cpp#L47

`std::numeric_limits<Real>::min()` gives the minimum possible _positive_ value, so that `UserHistoryOperation::max` won't give correct reductions over non positive values. The starting value should instead be `std::numeric_limits<Real>::lowest()`

**Comment by felker** [comment]
Thanks!
