### ISSUE TITLE
Vorticity calculation

### ISSUE THREAD

**Issue by JianhuaQin** [PrincetonUniversity/athena-public-version#69]
Dear Developers,

Thank you for providing this nice open source code. I enjoy using it.
Recently I am trying to calculate vorticity in Athena++.
However, the result seems to be different from the postprocessing result from Paraview.
Here is the code:
 ```
Real vorti = 0;
 int is=pmb->is, ie=pmb->ie, js=pmb->js, je=pmb->je, ks=pmb->ks, ke=pmb->ke;
 Real dx_local = pmb->pcoord->x1v(1) - pmb->pcoord->x1v(0);
 Real dy_local = pmb->pcoord->x2v(1) - pmb->pcoord->x2v(0);
 for(int k=ks; k<=ke; k++) {
   for(int j=js; j<=je; j++) { 
    for(int i=is; i<=ie; i++) {
	vorti = (pmb->phydro->w(IM2,k,j,i+1) - pmb->phydro->w(IM2,k,j,i-1))/(2.*dx_local) - 
		(pmb->phydro->w(IM1,k,j+1,i) - pmb->phydro->w(IM1,k,j-1,i))/(2.*dy_local);
    }
   }
 }
```
Coule you give any hint on any mistakes on the code?

Best,
Jianhua

**Comment by pdmullen** [comment]
Hi @JianhuaQin ! Hope you are well and happy holidays!

I wanted to confirm that you figured this one out. If not, I can share how I compute vorticity with Athena++.  

Best,
Patrick

**Comment by JianhuaQin** [comment]
Hello Patrick @pdmullen !

Thank you for your reply! I am sorry that I didn't get the notice of your response.
Currently, I still don't know how to solve this problem, hope you can share it to me whenever you are free.

Cheers,
Jianhua

**Comment by beresnyak** [comment]
couple of ideas:
phydro->w may not be updated at the time of your calculation (try using phydro->u)
your calculation involves ghost zones, does your output have ghost zones?

**Comment by JianhuaQin** [comment]
@beresnyak  Thanks for the suggestion. It doesn't seem to work #-.-
