### ISSUE TITLE
Inconsistent ordering of primitive variables in Wiki and actual HDF5 output

### ISSUE THREAD

**Issue by Yotag** [PrincetonUniversity/athena-public-version#7]
Hi!
I believe there is a slight mistake in the building of the XDMF files.
in the section of xdmf writing under "src/outputs/athena_hdf5.cpp"
" int n_quantity = 0;
    for (int n_dataset = 0; n_dataset < num_datasets; ++n_dataset) {
      for (int n_variable = 0; n_variable < num_variables[n_dataset]; ++n_variable) {
        xdmf << "    <Attribute Name=\"" << variable_names[n_quantity++]
            << "\" Center=\"Cell\">\n";"
the variables names are ordered rho, press, v1,v2,v3.
But in the actual HDF5 data structure you built it rho,v1,v2,v3,press, hence creating abit of a mess.
I will admit I am not quite fluent with the code yet, and I did some guess work of some of the structures but I am quite sure there is a little mess in the xdmf writing.
I would love to hear your thoughts!
Best wishes,
Yotam.

**Comment by c-white** [comment]
Both the .athdf file and the .xdmf file have the same ordering: rho, press, vel1, vel2, vel3.

I see the table on the wiki page lists them in a different order. That wasn't meant to show the order in the file, but I'll change it in the future for clarity.

In the spirit of HDF5 files being self-describing, the order in the file matches the file-level attribute `VariableNames`, which is a 1D array of strings.
