### ISSUE TITLE
Error when initializing mesh with spherical coordinates mesh and x1min=r=0.0

### ISSUE THREAD

**Issue by Yotag** [PrincetonUniversity/athena-public-version#8]
Good day!
 I am trying to run a blast simulation in spherical simulation with mpi, and I get a fatal error initializing Mesh trying to run the following input mesh:
```
<mesh>
nx1        = 640         # Number of zones in X1-direction
x1min      = 0.0        # minimum value of X1
x1max      = 100.0        # maximum value of X1
ix1_bc     = outflow    # inner-X1 boundary flag
ox1_bc     = outflow    # outer-X1 boundary flag

nx2        = 640             # Number of zones in X2-direction
x2min      = 0  # minimum value of X2
x2max      = 1.5708  # maximum value of X2
ix2_bc     = polar        # inner-X2 boundary flag
ox2_bc     = outflow        # outer-X2 boundary flag

nx3        = 640             # Number of zones in X3-direction
x3min      = 0 # minimum value of X3
x3max      = 6.283185307179586  # maximum value of X3
ix3_bc     = periodic        # inner-X3 boundary flag
ox3_bc     = periodic         # outer-X3 boundary flag
<meshblock>
nx1 = 320
nx2 = 320
nx3 = 320
```
I believe I have the boundary conditions right, but I still get a fatal error. 
I get the same error trying to run a full sphere:
```
x2min      = 0  # minimum value of X2
x2max      = 3.141592653589793 # maximum value of X2
ix2_bc     = polar        # inner-X2 boundary flag
ox2_bc     = polar       # outer-X2 boundary flag
```
Your help help with be appreciated.
Regards,
Yotam.

**Comment by c-white** [comment]
Spherical coordinates in Athena++ do not support going all the way to r = 0. If you want to simulate a sink at the origin, you need to choose a nonzero cutoff radius. In general, though, spherical coordinates may be a poor choice for a problem that goes close to the origin, since the timestep will be very small there.

If the problem persists after increasing `x1min`, please include the exact steps to replicate it, including the configure options used and the input file, as well as the error message.

**Comment by Yotag** [comment]
Thanks for the quick reply, I tried again without the origin, there were no issues.
I wish to create a simulation around the origin, with a gravitational field along the R direction. Naturally I went to the spherical coordinates first. How do you recommend proceeding ? Can it be only done in cartesian coordinates? constructing a gravitational pull from the origin would be more challenging without spherical coordinates, even your own point source is only available on spherical coordinates.
Thanks again for the support.
